[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_swap = { address = "6sicUYhh37rpGdLWQSrxRMshaUCgsteAHXcwn1jLmwUa", program_data_size = 32768 }

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/darrenhidalgo/personal/solana/SolanaDojo/token_swap/e2e_test/keys/deployer-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "target/types"
members = ["programs/*"]

[test.validator]
program_keypair = "target/deploy/token_swap-keypair.json"

[programs.mainnet]
token_swap = "AxNHE5L2X5PZoAU3To5tUQC2S7Z44RjeqAEwwe4FSWxa"

[programs.devnet]
token_swap = "AxNHE5L2X5PZoAU3To5tUQC2S7Z44RjeqAEwwe4FSWxa"
